# Setup
title:               ''
tagline:             why?
description:         ''
url:                 https://purak24.github.io/mywebsite
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              Purak Jain
  url:               https://twitter.com/purakjain
  email:             prkj24@gmail.com

# Gems
plugins:             [jekyll-seo-tag, jekyll-sitemap, jemoji]

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
