# Setup
title:               ''
tagline:             why?
description:         ''
url:                 https://purak24.github.io/mywebsite
baseurl:             '/mywebsite'
permalink:           pretty
# paginate:            2
#
# paginate_multiple:
#   - paginate: 3
#     paginate_path: '/page:num/'
#     sub_dir: '/blogs'
#   - paginate: 3
#     paginate_path: '/notes/page:num/'
#     sub_dir: '/notes'


# About/contact
author:
  name:              Purak Jain
  url:               https://twitter.com/purakjain
  email:             prkj24@gmail.com

# Gems
plugins:             [jekyll-seo-tag, jekyll-sitemap, jemoji]

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
