# Setup
title:               Purak
tagline:             ''
description:         ''
url:                 https://purak24.github.io/mywebsite
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Purak Jain
  url:               https://twitter.com/purakjain
  email:             prkj24@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
